name: MHCP Creator Doc Hub
title: MHCP Creator Documentation
description: Community-driven documentation for Horizon Worlds creators

# Base URL for GitHub Pages
url: "https://kells-sh.github.io"
baseurl: "/ben-worlds-documentation"

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Collections configuration for auto-discovery
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default values for all docs
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"