name: MHCP Creator Doc Hub
theme: jekyll-theme-minimal

# GitHub Pages compatibility
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-readme-index

# Syntax highlighting
highlighter: rouge
markdown: kramdown

# Collections configuration for auto-discovery
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default values for all docs
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"