name: MHCP Creator Doc Hub
title: MHCP Creator Documentation
description: Community-driven documentation for Horizon Worlds creators

# Remove theme - let GitHub Pages use default
# theme: jekyll-theme-minimal

# Base URL for GitHub Pages
url: "https://kells-sh.github.io"
baseurl: "/ben-worlds-documentation"

# GitHub Pages standard plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Syntax highlighting
highlighter: rouge
markdown: kramdown

# Kramdown settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections configuration for auto-discovery
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default values for all docs
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"