name: MHCP Creator Doc Hub
title: MHCP Creator Documentation
description: Community-driven documentation for Horizon Worlds creators

# Base URL for GitHub Pages
url: "https://kells-sh.github.io"
baseurl: "/ben-worlds-documentation"

# Add plugins for GitHub Pages
plugins:
  - jekyll-redirect-from

# Collections configuration for auto-discovery
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default values for all docs
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"